"""New Migration

Revision ID: 704807c3b920
Revises: da79ecbcc128
Create Date: 2021-12-12 16:50:02.648820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704807c3b920'
down_revision = 'da79ecbcc128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('middle_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'middle_name')
    # ### end Alembic commands ###
